# generated by datamodel-codegen:
#   filename:  patched.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel


class AgentStartEvent(BaseModel):
    type: Literal['agent_start']


class TurnStartEvent(BaseModel):
    type: Literal['turn_start']


class ToolExecutionStartEvent(BaseModel):
    args: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_start']


class ToolExecutionUpdateEvent(BaseModel):
    args: Any
    partialResult: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_update']


class ToolExecutionEndEvent(BaseModel):
    isError: bool
    result: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_end']


class QueueUpdateEvent(BaseModel):
    followUp: list[str]
    steering: list[str]
    type: Literal['queue_update']


class CompactionReason(Enum):
    manual = 'manual'
    threshold = 'threshold'
    overflow = 'overflow'


class CompactionStartEvent(BaseModel):
    reason: CompactionReason = Field(..., title='CompactionReason')
    type: Literal['compaction_start']


class SessionInfoChangedEvent(BaseModel):
    name: str | None = None
    type: Literal['session_info_changed']


class AutoRetryStartEvent(BaseModel):
    attempt: float
    delayMs: float
    errorMessage: str
    maxAttempts: float
    type: Literal['auto_retry_start']


class AutoRetryEndEvent(BaseModel):
    attempt: float
    finalError: str | None = None
    success: bool
    type: Literal['auto_retry_end']


class AssistantFinishReason(Enum):
    stop = 'stop'
    length = 'length'
    toolUse = 'toolUse'


class AssistantErrorReason(Enum):
    error = 'error'
    aborted = 'aborted'


class CompactionResult(BaseModel):
    details: Any | None = Field(
        None,
        description='Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction)',
    )
    firstKeptEntryId: str
    summary: str
    tokensBefore: float


class DiagnosticErrorInfo(BaseModel):
    code: str | float | None = None
    message: str
    name: str | None = None
    stack: str | None = None


class ImageContent(BaseModel):
    data: str
    mimeType: str
    type: Literal['image']


class KnownApi(Enum):
    openai_completions = 'openai-completions'
    mistral_conversations = 'mistral-conversations'
    openai_responses = 'openai-responses'
    azure_openai_responses = 'azure-openai-responses'
    openai_codex_responses = 'openai-codex-responses'
    anthropic_messages = 'anthropic-messages'
    bedrock_converse_stream = 'bedrock-converse-stream'
    google_generative_ai = 'google-generative-ai'
    google_vertex = 'google-vertex'


class KnownProvider(Enum):
    amazon_bedrock = 'amazon-bedrock'
    ant_ling = 'ant-ling'
    anthropic = 'anthropic'
    google = 'google'
    google_vertex = 'google-vertex'
    openai = 'openai'
    azure_openai_responses = 'azure-openai-responses'
    openai_codex = 'openai-codex'
    nvidia = 'nvidia'
    deepseek = 'deepseek'
    github_copilot = 'github-copilot'
    xai = 'xai'
    groq = 'groq'
    cerebras = 'cerebras'
    openrouter = 'openrouter'
    vercel_ai_gateway = 'vercel-ai-gateway'
    zai = 'zai'
    zai_coding_cn = 'zai-coding-cn'
    mistral = 'mistral'
    minimax = 'minimax'
    minimax_cn = 'minimax-cn'
    moonshotai = 'moonshotai'
    moonshotai_cn = 'moonshotai-cn'
    huggingface = 'huggingface'
    fireworks = 'fireworks'
    together = 'together'
    opencode = 'opencode'
    opencode_go = 'opencode-go'
    kimi_coding = 'kimi-coding'
    cloudflare_workers_ai = 'cloudflare-workers-ai'
    cloudflare_ai_gateway = 'cloudflare-ai-gateway'
    xiaomi = 'xiaomi'
    xiaomi_token_plan_cn = 'xiaomi-token-plan-cn'
    xiaomi_token_plan_ams = 'xiaomi-token-plan-ams'
    xiaomi_token_plan_sgp = 'xiaomi-token-plan-sgp'


class StopReason(Enum):
    stop = 'stop'
    length = 'length'
    toolUse = 'toolUse'
    error = 'error'
    aborted = 'aborted'


class TextContent(BaseModel):
    text: str
    textSignature: str | None = None
    type: Literal['text']


class ThinkingContent(BaseModel):
    redacted: bool | None = Field(
        None,
        description='When true, the thinking content was redacted by safety filters. The opaque encrypted payload is stored in `thinkingSignature` so it can be passed back to the API for multi-turn continuity.',
    )
    thinking: str
    thinkingSignature: str | None = None
    type: Literal['thinking']


class ThinkingLevel(Enum):
    off = 'off'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class ToolCall(BaseModel):
    arguments: dict[str, Any]
    id: str
    name: str
    thoughtSignature: str | None = None
    type: Literal['toolCall']


class ToolResultMessage(BaseModel):
    content: list[TextContent | ImageContent]
    details: Any | None = None
    isError: bool
    role: Literal['toolResult']
    timestamp: float
    toolCallId: str
    toolName: str


class Cost(BaseModel):
    cacheRead: float
    cacheWrite: float
    input: float
    output: float
    total: float


class Usage(BaseModel):
    cacheRead: float
    cacheWrite: float
    cost: Cost
    input: float
    output: float
    totalTokens: float


class UserMessage(BaseModel):
    content: str | list[TextContent | ImageContent]
    role: Literal['user']
    timestamp: float


class ThinkingLevelChangedEvent(BaseModel):
    level: ThinkingLevel
    type: Literal['thinking_level_changed']


class CompactionEndEvent(BaseModel):
    aborted: bool
    errorMessage: str | None = None
    reason: CompactionReason = Field(..., title='CompactionReason')
    result: CompactionResult | None = None
    type: Literal['compaction_end']
    willRetry: bool


class AssistantMessageDiagnostic(BaseModel):
    details: dict[str, Any] | None = None
    error: DiagnosticErrorInfo | None = None
    timestamp: float
    type: str


class AssistantMessage(BaseModel):
    api: KnownApi | str
    content: list[TextContent | ThinkingContent | ToolCall]
    diagnostics: list[AssistantMessageDiagnostic] | None = None
    errorMessage: str | None = None
    model: str
    provider: KnownProvider | str
    responseId: str | None = None
    responseModel: str | None = None
    role: Literal['assistant']
    stopReason: StopReason
    timestamp: float
    usage: Usage


class AssistantMessageStart(BaseModel):
    partial: AssistantMessage
    type: Literal['start']


class AssistantMessageTextStart(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    type: Literal['text_start']


class AssistantMessageTextDelta(BaseModel):
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['text_delta']


class AssistantMessageTextEnd(BaseModel):
    content: str
    contentIndex: float
    partial: AssistantMessage
    type: Literal['text_end']


class AssistantMessageThinkingStart(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    type: Literal['thinking_start']


class AssistantMessageThinkingDelta(BaseModel):
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['thinking_delta']


class AssistantMessageThinkingEnd(BaseModel):
    content: str
    contentIndex: float
    partial: AssistantMessage
    type: Literal['thinking_end']


class AssistantMessageToolcallStart(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    type: Literal['toolcall_start']


class AssistantMessageToolcallDelta(BaseModel):
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['toolcall_delta']


class AssistantMessageToolcallEnd(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    toolCall: ToolCall
    type: Literal['toolcall_end']


class AssistantMessageDone(BaseModel):
    message: AssistantMessage
    reason: AssistantFinishReason = Field(..., title='AssistantFinishReason')
    type: Literal['done']


class AssistantMessageError(BaseModel):
    error: AssistantMessage
    reason: AssistantErrorReason = Field(..., title='AssistantErrorReason')
    type: Literal['error']


class TurnEndEvent(BaseModel):
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    toolResults: list[ToolResultMessage]
    type: Literal['turn_end']


class MessageStartEvent(BaseModel):
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    type: Literal['message_start']


class MessageUpdateEvent(BaseModel):
    assistantMessageEvent: (
        AssistantMessageStart
        | AssistantMessageTextStart
        | AssistantMessageTextDelta
        | AssistantMessageTextEnd
        | AssistantMessageThinkingStart
        | AssistantMessageThinkingDelta
        | AssistantMessageThinkingEnd
        | AssistantMessageToolcallStart
        | AssistantMessageToolcallDelta
        | AssistantMessageToolcallEnd
        | AssistantMessageDone
        | AssistantMessageError
    ) = Field(
        ...,
        description='Event protocol for AssistantMessageEventStream.\n\nStreams should emit `start` before partial updates, then terminate with either:\n- `done` carrying the final successful AssistantMessage, or\n- `error` carrying the final AssistantMessage with stopReason "error" or "aborted"   and errorMessage.',
    )
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    type: Literal['message_update']


class MessageEndEvent(BaseModel):
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    type: Literal['message_end']


class AgentEndEvent(BaseModel):
    messages: list[UserMessage | AssistantMessage | ToolResultMessage]
    type: Literal['agent_end']
    willRetry: bool


class AgentSessionEvent(
    RootModel[
        AgentStartEvent
        | TurnStartEvent
        | TurnEndEvent
        | MessageStartEvent
        | MessageUpdateEvent
        | MessageEndEvent
        | ToolExecutionStartEvent
        | ToolExecutionUpdateEvent
        | ToolExecutionEndEvent
        | AgentEndEvent
        | QueueUpdateEvent
        | CompactionStartEvent
        | SessionInfoChangedEvent
        | ThinkingLevelChangedEvent
        | CompactionEndEvent
        | AutoRetryStartEvent
        | AutoRetryEndEvent
    ]
):
    root: (
        AgentStartEvent
        | TurnStartEvent
        | TurnEndEvent
        | MessageStartEvent
        | MessageUpdateEvent
        | MessageEndEvent
        | ToolExecutionStartEvent
        | ToolExecutionUpdateEvent
        | ToolExecutionEndEvent
        | AgentEndEvent
        | QueueUpdateEvent
        | CompactionStartEvent
        | SessionInfoChangedEvent
        | ThinkingLevelChangedEvent
        | CompactionEndEvent
        | AutoRetryStartEvent
        | AutoRetryEndEvent
    ) = Field(
        ..., description='Session-specific events that extend the core AgentEvent'
    )
