# generated by datamodel-codegen:
#   filename:  agent-session.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AgentSessionEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['agent_start']


class AgentSessionEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['turn_start']


class AgentSessionEvent7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_start']


class AgentSessionEvent8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any
    partialResult: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_update']


class AgentSessionEvent9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: bool
    result: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_end']


class AgentSessionEvent11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    followUp: list[str]
    steering: list[str]
    type: Literal['queue_update']


class Reason(Enum):
    manual = 'manual'
    threshold = 'threshold'
    overflow = 'overflow'


class AgentSessionEvent12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: Reason
    type: Literal['compaction_start']


class AgentSessionEvent13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    type: Literal['session_info_changed']


class AgentSessionEvent16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: float
    delayMs: float
    errorMessage: str
    maxAttempts: float
    type: Literal['auto_retry_start']


class AgentSessionEvent17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: float
    finalError: str | None = None
    success: bool
    type: Literal['auto_retry_end']


class Reason2(Enum):
    stop = 'stop'
    length = 'length'
    toolUse = 'toolUse'


class Reason3(Enum):
    error = 'error'
    aborted = 'aborted'


class CompactionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    details: Any | None = Field(
        None,
        description='Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction)',
    )
    firstKeptEntryId: str
    summary: str
    tokensBefore: float


class DiagnosticErrorInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str | float | None = None
    message: str
    name: str | None = None
    stack: str | None = None


class ImageContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    mimeType: str
    type: Literal['image']


class KnownApi(Enum):
    openai_completions = 'openai-completions'
    mistral_conversations = 'mistral-conversations'
    openai_responses = 'openai-responses'
    azure_openai_responses = 'azure-openai-responses'
    openai_codex_responses = 'openai-codex-responses'
    anthropic_messages = 'anthropic-messages'
    bedrock_converse_stream = 'bedrock-converse-stream'
    google_generative_ai = 'google-generative-ai'
    google_vertex = 'google-vertex'


class KnownProvider(Enum):
    amazon_bedrock = 'amazon-bedrock'
    ant_ling = 'ant-ling'
    anthropic = 'anthropic'
    google = 'google'
    google_vertex = 'google-vertex'
    openai = 'openai'
    azure_openai_responses = 'azure-openai-responses'
    openai_codex = 'openai-codex'
    nvidia = 'nvidia'
    deepseek = 'deepseek'
    github_copilot = 'github-copilot'
    xai = 'xai'
    groq = 'groq'
    cerebras = 'cerebras'
    openrouter = 'openrouter'
    vercel_ai_gateway = 'vercel-ai-gateway'
    zai = 'zai'
    zai_coding_cn = 'zai-coding-cn'
    mistral = 'mistral'
    minimax = 'minimax'
    minimax_cn = 'minimax-cn'
    moonshotai = 'moonshotai'
    moonshotai_cn = 'moonshotai-cn'
    huggingface = 'huggingface'
    fireworks = 'fireworks'
    together = 'together'
    opencode = 'opencode'
    opencode_go = 'opencode-go'
    kimi_coding = 'kimi-coding'
    cloudflare_workers_ai = 'cloudflare-workers-ai'
    cloudflare_ai_gateway = 'cloudflare-ai-gateway'
    xiaomi = 'xiaomi'
    xiaomi_token_plan_cn = 'xiaomi-token-plan-cn'
    xiaomi_token_plan_ams = 'xiaomi-token-plan-ams'
    xiaomi_token_plan_sgp = 'xiaomi-token-plan-sgp'


class Provider(RootModel[KnownProvider | str]):
    root: KnownProvider | str


class StopReason(Enum):
    stop = 'stop'
    length = 'length'
    toolUse = 'toolUse'
    error = 'error'
    aborted = 'aborted'


class TextContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    textSignature: str | None = None
    type: Literal['text']


class ThinkingContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    redacted: bool | None = Field(
        None,
        description='When true, the thinking content was redacted by safety filters. The opaque encrypted payload is stored in `thinkingSignature` so it can be passed back to the API for multi-turn continuity.',
    )
    thinking: str
    thinkingSignature: str | None = None
    type: Literal['thinking']


class ThinkingLevel(Enum):
    off = 'off'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: dict[str, Any]
    id: str
    name: str
    thoughtSignature: str | None = None
    type: Literal['toolCall']


class ToolResultMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: list[TextContent | ImageContent]
    details: Any | None = None
    isError: bool
    role: Literal['toolResult']
    timestamp: float
    toolCallId: str
    toolName: str


class Cost(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cacheRead: float
    cacheWrite: float
    input: float
    output: float
    total: float


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cacheRead: float
    cacheWrite: float
    cost: Cost
    input: float
    output: float
    totalTokens: float


class UserMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str | list[TextContent | ImageContent]
    role: Literal['user']
    timestamp: float


class AgentSessionEvent14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: ThinkingLevel
    type: Literal['thinking_level_changed']


class AgentSessionEvent15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aborted: bool
    errorMessage: str | None = None
    reason: Reason
    result: CompactionResult | None = None
    type: Literal['compaction_end']
    willRetry: bool


class Api(RootModel[KnownApi | str]):
    root: KnownApi | str


class AssistantMessageDiagnostic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    details: dict[str, Any] | None = None
    error: DiagnosticErrorInfo | None = None
    timestamp: float
    type: str


class AssistantMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api: Api
    content: list[TextContent | ThinkingContent | ToolCall]
    diagnostics: list[AssistantMessageDiagnostic] | None = None
    errorMessage: str | None = None
    model: str
    provider: Provider
    responseId: str | None = None
    responseModel: str | None = None
    role: Literal['assistant']
    stopReason: StopReason
    timestamp: float
    usage: Usage


class AssistantMessageEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    partial: AssistantMessage
    type: Literal['start']


class AssistantMessageEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    partial: AssistantMessage
    type: Literal['text_start']


class AssistantMessageEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['text_delta']


class AssistantMessageEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str
    contentIndex: float
    partial: AssistantMessage
    type: Literal['text_end']


class AssistantMessageEvent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    partial: AssistantMessage
    type: Literal['thinking_start']


class AssistantMessageEvent6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['thinking_delta']


class AssistantMessageEvent7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str
    contentIndex: float
    partial: AssistantMessage
    type: Literal['thinking_end']


class AssistantMessageEvent8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    partial: AssistantMessage
    type: Literal['toolcall_start']


class AssistantMessageEvent9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['toolcall_delta']


class AssistantMessageEvent10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentIndex: float
    partial: AssistantMessage
    toolCall: ToolCall
    type: Literal['toolcall_end']


class AssistantMessageEvent11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: AssistantMessage
    reason: Reason2
    type: Literal['done']


class AssistantMessageEvent12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: AssistantMessage
    reason: Reason3
    type: Literal['error']


class AssistantMessageEvent(
    RootModel[
        AssistantMessageEvent1
        | AssistantMessageEvent2
        | AssistantMessageEvent3
        | AssistantMessageEvent4
        | AssistantMessageEvent5
        | AssistantMessageEvent6
        | AssistantMessageEvent7
        | AssistantMessageEvent8
        | AssistantMessageEvent9
        | AssistantMessageEvent10
        | AssistantMessageEvent11
        | AssistantMessageEvent12
    ]
):
    root: (
        AssistantMessageEvent1
        | AssistantMessageEvent2
        | AssistantMessageEvent3
        | AssistantMessageEvent4
        | AssistantMessageEvent5
        | AssistantMessageEvent6
        | AssistantMessageEvent7
        | AssistantMessageEvent8
        | AssistantMessageEvent9
        | AssistantMessageEvent10
        | AssistantMessageEvent11
        | AssistantMessageEvent12
    ) = Field(
        ...,
        description='Event protocol for AssistantMessageEventStream.\n\nStreams should emit `start` before partial updates, then terminate with either:\n- `done` carrying the final successful AssistantMessage, or\n- `error` carrying the final AssistantMessage with stopReason "error" or "aborted"   and errorMessage.',
    )


class Message(RootModel[UserMessage | AssistantMessage | ToolResultMessage]):
    root: UserMessage | AssistantMessage | ToolResultMessage


class AgentMessage(RootModel[Message]):
    root: Message = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )


class AgentSessionEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: AgentMessage
    toolResults: list[ToolResultMessage]
    type: Literal['turn_end']


class AgentSessionEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: AgentMessage
    type: Literal['message_start']


class AgentSessionEvent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assistantMessageEvent: AssistantMessageEvent
    message: AgentMessage
    type: Literal['message_update']


class AgentSessionEvent6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: AgentMessage
    type: Literal['message_end']


class AgentSessionEvent10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messages: list[AgentMessage]
    type: Literal['agent_end']
    willRetry: bool


class AgentSessionEvent(
    RootModel[
        AgentSessionEvent1
        | AgentSessionEvent2
        | AgentSessionEvent3
        | AgentSessionEvent4
        | AgentSessionEvent5
        | AgentSessionEvent6
        | AgentSessionEvent7
        | AgentSessionEvent8
        | AgentSessionEvent9
        | AgentSessionEvent10
        | AgentSessionEvent11
        | AgentSessionEvent12
        | AgentSessionEvent13
        | AgentSessionEvent14
        | AgentSessionEvent15
        | AgentSessionEvent16
        | AgentSessionEvent17
    ]
):
    root: (
        AgentSessionEvent1
        | AgentSessionEvent2
        | AgentSessionEvent3
        | AgentSessionEvent4
        | AgentSessionEvent5
        | AgentSessionEvent6
        | AgentSessionEvent7
        | AgentSessionEvent8
        | AgentSessionEvent9
        | AgentSessionEvent10
        | AgentSessionEvent11
        | AgentSessionEvent12
        | AgentSessionEvent13
        | AgentSessionEvent14
        | AgentSessionEvent15
        | AgentSessionEvent16
        | AgentSessionEvent17
    ) = Field(
        ..., description='Session-specific events that extend the core AgentEvent'
    )


class Model(RootModel[AgentSessionEvent]):
    root: AgentSessionEvent
