# generated by datamodel-codegen:
#   filename:  patched.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel


class FieldRpcSchema(RootModel[Any]):
    root: Any


class AgentStartEvent(BaseModel):
    type: Literal['agent_start']


class TurnStartEvent(BaseModel):
    type: Literal['turn_start']


class ToolExecutionStartEvent(BaseModel):
    args: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_start']


class ToolExecutionUpdateEvent(BaseModel):
    args: Any
    partialResult: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_update']


class ToolExecutionEndEvent(BaseModel):
    isError: bool
    result: Any
    toolCallId: str
    toolName: str
    type: Literal['tool_execution_end']


class QueueUpdateEvent(BaseModel):
    followUp: list[str]
    steering: list[str]
    type: Literal['queue_update']


class CompactionReason(Enum):
    manual = 'manual'
    threshold = 'threshold'
    overflow = 'overflow'


class CompactionStartEvent(BaseModel):
    reason: CompactionReason = Field(..., title='CompactionReason')
    type: Literal['compaction_start']


class SessionInfoChangedEvent(BaseModel):
    name: str | None = None
    type: Literal['session_info_changed']


class AutoRetryStartEvent(BaseModel):
    attempt: float
    delayMs: float
    errorMessage: str
    maxAttempts: float
    type: Literal['auto_retry_start']


class AutoRetryEndEvent(BaseModel):
    attempt: float
    finalError: str | None = None
    success: bool
    type: Literal['auto_retry_end']


class AssistantFinishReason(Enum):
    stop = 'stop'
    length = 'length'
    toolUse = 'toolUse'


class AssistantErrorReason(Enum):
    error = 'error'
    aborted = 'aborted'


class BashResult(BaseModel):
    cancelled: bool = Field(
        ..., description='Whether the command was cancelled via signal'
    )
    exitCode: float | None = Field(
        None, description='Process exit code (undefined if killed/cancelled)'
    )
    fullOutputPath: str | None = Field(
        None,
        description='Path to temp file containing full output (if output exceeded truncation threshold)',
    )
    output: str = Field(
        ...,
        description='Combined stdout + stderr output (sanitized, possibly truncated)',
    )
    truncated: bool = Field(..., description='Whether the output was truncated')


class CompactionResult(BaseModel):
    details: Any | None = Field(
        None,
        description='Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction)',
    )
    firstKeptEntryId: str
    summary: str
    tokensBefore: float


class ContextUsage(BaseModel):
    contextWindow: float
    percent: float | None = Field(
        ...,
        description='Context usage as percentage of context window, or null if tokens is unknown.',
    )
    tokens: float | None = Field(
        ...,
        description='Estimated context tokens, or null if unknown (e.g. right after compaction, before next LLM response).',
    )


class DiagnosticErrorInfo(BaseModel):
    code: str | float | None = None
    message: str
    name: str | None = None
    stack: str | None = None


class ImageContent(BaseModel):
    data: str
    mimeType: str
    type: Literal['image']


class KnownApi(Enum):
    openai_completions = 'openai-completions'
    mistral_conversations = 'mistral-conversations'
    openai_responses = 'openai-responses'
    azure_openai_responses = 'azure-openai-responses'
    openai_codex_responses = 'openai-codex-responses'
    anthropic_messages = 'anthropic-messages'
    bedrock_converse_stream = 'bedrock-converse-stream'
    google_generative_ai = 'google-generative-ai'
    google_vertex = 'google-vertex'


class KnownProvider(Enum):
    amazon_bedrock = 'amazon-bedrock'
    ant_ling = 'ant-ling'
    anthropic = 'anthropic'
    google = 'google'
    google_vertex = 'google-vertex'
    openai = 'openai'
    azure_openai_responses = 'azure-openai-responses'
    openai_codex = 'openai-codex'
    nvidia = 'nvidia'
    deepseek = 'deepseek'
    github_copilot = 'github-copilot'
    xai = 'xai'
    groq = 'groq'
    cerebras = 'cerebras'
    openrouter = 'openrouter'
    vercel_ai_gateway = 'vercel-ai-gateway'
    zai = 'zai'
    zai_coding_cn = 'zai-coding-cn'
    mistral = 'mistral'
    minimax = 'minimax'
    minimax_cn = 'minimax-cn'
    moonshotai = 'moonshotai'
    moonshotai_cn = 'moonshotai-cn'
    huggingface = 'huggingface'
    fireworks = 'fireworks'
    together = 'together'
    opencode = 'opencode'
    opencode_go = 'opencode-go'
    kimi_coding = 'kimi-coding'
    cloudflare_workers_ai = 'cloudflare-workers-ai'
    cloudflare_ai_gateway = 'cloudflare-ai-gateway'
    xiaomi = 'xiaomi'
    xiaomi_token_plan_cn = 'xiaomi-token-plan-cn'
    xiaomi_token_plan_ams = 'xiaomi-token-plan-ams'
    xiaomi_token_plan_sgp = 'xiaomi-token-plan-sgp'


class MaxTokensField(Enum):
    max_completion_tokens = 'max_completion_tokens'
    max_tokens = 'max_tokens'


class ThinkingFormat(Enum):
    openai = 'openai'
    openrouter = 'openrouter'
    deepseek = 'deepseek'
    together = 'together'
    zai = 'zai'
    qwen = 'qwen'
    qwen_chat_template = 'qwen-chat-template'
    string_thinking = 'string-thinking'
    ant_ling = 'ant-ling'


class DataCollection(Enum):
    deny = 'deny'
    allow = 'allow'


class MaxPrice(BaseModel):
    audio: float | str | None = Field(None, description='Price per audio unit.')
    completion: float | str | None = Field(
        None, description='Price per million completion tokens.'
    )
    image: float | str | None = Field(None, description='Price per image.')
    prompt: float | str | None = Field(
        None, description='Price per million prompt tokens.'
    )
    request: float | str | None = Field(None, description='Price per request.')


class PreferredMaxLatency(BaseModel):
    p50: float | None = Field(
        None, description='Maximum latency in seconds at the 50th percentile.'
    )
    p75: float | None = Field(
        None, description='Maximum latency in seconds at the 75th percentile.'
    )
    p90: float | None = Field(
        None, description='Maximum latency in seconds at the 90th percentile.'
    )
    p99: float | None = Field(
        None, description='Maximum latency in seconds at the 99th percentile.'
    )


class PreferredMinThroughput(BaseModel):
    p50: float | None = Field(
        None, description='Minimum tokens/second at the 50th percentile.'
    )
    p75: float | None = Field(
        None, description='Minimum tokens/second at the 75th percentile.'
    )
    p90: float | None = Field(
        None, description='Minimum tokens/second at the 90th percentile.'
    )
    p99: float | None = Field(
        None, description='Minimum tokens/second at the 99th percentile.'
    )


class Sort(BaseModel):
    by: str | None = Field(
        None, description='The sorting metric: "price", "throughput", "latency".'
    )
    partition: str | None = Field(
        None, description='Partitioning strategy: "model" (default) or "none".'
    )


class OpenRouterRouting(BaseModel):
    allow_fallbacks: bool | None = Field(
        None,
        description='Whether to allow backup providers to serve requests. Default: true.',
    )
    data_collection: DataCollection | None = Field(
        None,
        description='Data collection setting. "allow" (default): allow providers that may store/train on data. "deny": only use providers that don\'t collect user data.',
    )
    enforce_distillable_text: bool | None = Field(
        None,
        description='Whether to restrict routing to only models that allow text distillation.',
    )
    ignore: list[str] | None = Field(
        None, description='List of provider names/slugs to skip for this request.'
    )
    max_price: MaxPrice | None = Field(
        None, description='Maximum price per million tokens (USD).'
    )
    only: list[str] | None = Field(
        None,
        description='List of provider names/slugs to exclusively allow for this request.',
    )
    order: list[str] | None = Field(
        None,
        description='An ordered list of provider names/slugs to try in sequence, falling back to the next if unavailable.',
    )
    preferred_max_latency: float | PreferredMaxLatency | None = Field(
        None,
        description='Preferred maximum latency (seconds). Can be a number (applies to p50) or an object with percentile-specific cutoffs.',
    )
    preferred_min_throughput: float | PreferredMinThroughput | None = Field(
        None,
        description='Preferred minimum throughput (tokens/second). Can be a number (applies to p50) or an object with percentile-specific cutoffs.',
    )
    quantizations: list[str] | None = Field(
        None,
        description='A list of quantization levels to filter providers by (e.g., ["fp16", "bf16", "fp8", "fp6", "int8", "int4", "fp4", "fp32"]).',
    )
    require_parameters: bool | None = Field(
        None,
        description='Whether to filter providers to only those that support all parameters in the request. Default: false.',
    )
    sort: str | Sort | None = Field(
        None,
        description='Sorting strategy. Can be a string (e.g., "price", "throughput", "latency") or an object with `by` and `partition`.',
    )
    zdr: bool | None = Field(
        None,
        description='Whether to restrict routing to only ZDR (Zero Data Retention) endpoints.',
    )


class StreamingBehavior(Enum):
    steer = 'steer'
    followUp = 'followUp'


class PromptCommand(BaseModel):
    id: str | None = None
    images: list[ImageContent] | None = None
    message: str
    streamingBehavior: StreamingBehavior | None = Field(None, title='StreamingBehavior')
    type: Literal['prompt']


class SteerCommand(BaseModel):
    id: str | None = None
    images: list[ImageContent] | None = None
    message: str
    type: Literal['steer']


class FollowUpCommand(BaseModel):
    id: str | None = None
    images: list[ImageContent] | None = None
    message: str
    type: Literal['follow_up']


class AbortCommand(BaseModel):
    id: str | None = None
    type: Literal['abort']


class NewSessionCommand(BaseModel):
    id: str | None = None
    parentSession: str | None = None
    type: Literal['new_session']


class GetStateCommand(BaseModel):
    id: str | None = None
    type: Literal['get_state']


class SetModelCommand(BaseModel):
    id: str | None = None
    modelId: str
    provider: str
    type: Literal['set_model']


class CycleModelCommand(BaseModel):
    id: str | None = None
    type: Literal['cycle_model']


class GetAvailableModelsCommand(BaseModel):
    id: str | None = None
    type: Literal['get_available_models']


class CycleThinkingLevelCommand(BaseModel):
    id: str | None = None
    type: Literal['cycle_thinking_level']


class QueueMode(Enum):
    all = 'all'
    one_at_a_time = 'one-at-a-time'


class SetSteeringModeCommand(BaseModel):
    id: str | None = None
    mode: QueueMode = Field(..., title='QueueMode')
    type: Literal['set_steering_mode']


class SetFollowUpModeCommand(BaseModel):
    id: str | None = None
    mode: QueueMode = Field(..., title='QueueMode')
    type: Literal['set_follow_up_mode']


class CompactCommand(BaseModel):
    customInstructions: str | None = None
    id: str | None = None
    type: Literal['compact']


class SetAutoCompactionCommand(BaseModel):
    enabled: bool
    id: str | None = None
    type: Literal['set_auto_compaction']


class SetAutoRetryCommand(BaseModel):
    enabled: bool
    id: str | None = None
    type: Literal['set_auto_retry']


class AbortRetryCommand(BaseModel):
    id: str | None = None
    type: Literal['abort_retry']


class BashCommand(BaseModel):
    command: str
    excludeFromContext: bool | None = None
    id: str | None = None
    type: Literal['bash']


class AbortBashCommand(BaseModel):
    id: str | None = None
    type: Literal['abort_bash']


class GetSessionStatsCommand(BaseModel):
    id: str | None = None
    type: Literal['get_session_stats']


class ExportHtmlCommand(BaseModel):
    id: str | None = None
    outputPath: str | None = None
    type: Literal['export_html']


class SwitchSessionCommand(BaseModel):
    id: str | None = None
    sessionPath: str
    type: Literal['switch_session']


class ForkCommand(BaseModel):
    entryId: str
    id: str | None = None
    type: Literal['fork']


class CloneCommand(BaseModel):
    id: str | None = None
    type: Literal['clone']


class GetForkMessagesCommand(BaseModel):
    id: str | None = None
    type: Literal['get_fork_messages']


class GetLastAssistantTextCommand(BaseModel):
    id: str | None = None
    type: Literal['get_last_assistant_text']


class SetSessionNameCommand(BaseModel):
    id: str | None = None
    name: str
    type: Literal['set_session_name']


class GetMessagesCommand(BaseModel):
    id: str | None = None
    type: Literal['get_messages']


class GetCommandsCommand(BaseModel):
    id: str | None = None
    type: Literal['get_commands']


class PromptResponse(BaseModel):
    command: Literal['prompt']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SteerResponse(BaseModel):
    command: Literal['steer']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class FollowUpResponse(BaseModel):
    command: Literal['follow_up']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class AbortResponse(BaseModel):
    command: Literal['abort']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class NewSessionResult(BaseModel):
    cancelled: bool


class NewSessionResponse(BaseModel):
    command: Literal['new_session']
    data: NewSessionResult = Field(..., title='NewSessionResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SetThinkingLevelResponse(BaseModel):
    command: Literal['set_thinking_level']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SetSteeringModeResponse(BaseModel):
    command: Literal['set_steering_mode']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SetFollowUpModeResponse(BaseModel):
    command: Literal['set_follow_up_mode']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class CompactResponse(BaseModel):
    command: Literal['compact']
    data: CompactionResult
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SetAutoCompactionResponse(BaseModel):
    command: Literal['set_auto_compaction']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SetAutoRetryResponse(BaseModel):
    command: Literal['set_auto_retry']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class AbortRetryResponse(BaseModel):
    command: Literal['abort_retry']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class BashResponse(BaseModel):
    command: Literal['bash']
    data: BashResult
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class AbortBashResponse(BaseModel):
    command: Literal['abort_bash']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class ExportHtmlResult(BaseModel):
    path: str


class ExportHtmlResponse(BaseModel):
    command: Literal['export_html']
    data: ExportHtmlResult = Field(..., title='ExportHtmlResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SwitchSessionResult(BaseModel):
    cancelled: bool


class SwitchSessionResponse(BaseModel):
    command: Literal['switch_session']
    data: SwitchSessionResult = Field(..., title='SwitchSessionResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class ForkResult(BaseModel):
    cancelled: bool
    text: str


class ForkResponse(BaseModel):
    command: Literal['fork']
    data: ForkResult = Field(..., title='ForkResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class CloneResult(BaseModel):
    cancelled: bool


class CloneResponse(BaseModel):
    command: Literal['clone']
    data: CloneResult = Field(..., title='CloneResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class Message1(BaseModel):
    entryId: str
    text: str


class ForkMessagesResult(BaseModel):
    messages: list[Message1]


class GetForkMessagesResponse(BaseModel):
    command: Literal['get_fork_messages']
    data: ForkMessagesResult = Field(..., title='ForkMessagesResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class LastAssistantTextResult(BaseModel):
    text: str | None


class GetLastAssistantTextResponse(BaseModel):
    command: Literal['get_last_assistant_text']
    data: LastAssistantTextResult = Field(..., title='LastAssistantTextResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SetSessionNameResponse(BaseModel):
    command: Literal['set_session_name']
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class RpcErrorResponse(BaseModel):
    command: str
    error: str
    id: str | None = None
    success: Literal[False]
    type: Literal['response']


class FollowUpMode(Enum):
    all = 'all'
    one_at_a_time = 'one-at-a-time'


class SteeringMode(Enum):
    all = 'all'
    one_at_a_time = 'one-at-a-time'


class Source(Enum):
    extension = 'extension'
    prompt = 'prompt'
    skill = 'skill'


class Tokens(BaseModel):
    cacheRead: float
    cacheWrite: float
    input: float
    output: float
    total: float


class SessionStats(BaseModel):
    assistantMessages: float
    contextUsage: ContextUsage | None = None
    cost: float
    sessionFile: str | None = None
    sessionId: str
    tokens: Tokens
    toolCalls: float
    toolResults: float
    totalMessages: float
    userMessages: float


class SourceOrigin(Enum):
    package = 'package'
    top_level = 'top-level'


class SourceScope(Enum):
    user = 'user'
    project = 'project'
    temporary = 'temporary'


class StopReason(Enum):
    stop = 'stop'
    length = 'length'
    toolUse = 'toolUse'
    error = 'error'
    aborted = 'aborted'


class TextContent(BaseModel):
    text: str
    textSignature: str | None = None
    type: Literal['text']


class ThinkingContent(BaseModel):
    redacted: bool | None = Field(
        None,
        description='When true, the thinking content was redacted by safety filters. The opaque encrypted payload is stored in `thinkingSignature` so it can be passed back to the API for multi-turn continuity.',
    )
    thinking: str
    thinkingSignature: str | None = None
    type: Literal['thinking']


class ThinkingLevel(Enum):
    off = 'off'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class ThinkingLevelMap(BaseModel):
    high: str | None = None
    low: str | None = None
    medium: str | None = None
    minimal: str | None = None
    off: str | None = None
    xhigh: str | None = None


class ToolCall(BaseModel):
    arguments: dict[str, Any]
    id: str
    name: str
    thoughtSignature: str | None = None
    type: Literal['toolCall']


class ToolResultMessage(BaseModel):
    content: list[TextContent | ImageContent]
    details: Any | None = None
    isError: bool
    role: Literal['toolResult']
    timestamp: float
    toolCallId: str
    toolName: str


class Cost(BaseModel):
    cacheRead: float
    cacheWrite: float
    input: float
    output: float
    total: float


class Usage(BaseModel):
    cacheRead: float
    cacheWrite: float
    cost: Cost
    input: float
    output: float
    totalTokens: float


class UserMessage(BaseModel):
    content: str | list[TextContent | ImageContent]
    role: Literal['user']
    timestamp: float


class VercelGatewayRouting(BaseModel):
    only: list[str] | None = Field(
        None,
        description='List of provider slugs to exclusively use for this request (e.g., ["bedrock", "anthropic"]).',
    )
    order: list[str] | None = Field(
        None,
        description='List of provider slugs to try in order (e.g., ["anthropic", "openai"]).',
    )


class Cost1(BaseModel):
    cacheRead: float
    cacheWrite: float
    input: float
    output: float


class InputEnum(Enum):
    text = 'text'
    image = 'image'


class ThinkingLevelChangedEvent(BaseModel):
    level: ThinkingLevel
    type: Literal['thinking_level_changed']


class CompactionEndEvent(BaseModel):
    aborted: bool
    errorMessage: str | None = None
    reason: CompactionReason = Field(..., title='CompactionReason')
    result: CompactionResult | None = None
    type: Literal['compaction_end']
    willRetry: bool


class AssistantMessageDiagnostic(BaseModel):
    details: dict[str, Any] | None = None
    error: DiagnosticErrorInfo | None = None
    timestamp: float
    type: str


class OpenAICompletionsCompat(BaseModel):
    cacheControlFormat: Literal['anthropic'] = Field(
        'anthropic',
        description='Cache control convention for prompt caching. "anthropic" applies Anthropic-style `cache_control` markers to the system prompt, last tool definition, and last user/assistant text content.',
    )
    maxTokensField: MaxTokensField | None = Field(
        None,
        description='Which field to use for max tokens. Default: auto-detected from URL.',
    )
    openRouterRouting: OpenRouterRouting | None = Field(
        None,
        description='OpenRouter-specific routing preferences. Only used when baseUrl points to OpenRouter.',
    )
    requiresAssistantAfterToolResult: bool | None = Field(
        None,
        description='Whether a user message after tool results requires an assistant message in between. Default: auto-detected from URL.',
    )
    requiresReasoningContentOnAssistantMessages: bool | None = Field(
        None,
        description='Whether all replayed assistant messages must include an empty reasoning_content field when reasoning is enabled. Default: auto-detected from URL.',
    )
    requiresThinkingAsText: bool | None = Field(
        None,
        description='Whether thinking blocks must be converted to text blocks with <thinking> delimiters. Default: auto-detected from URL.',
    )
    requiresToolResultName: bool | None = Field(
        None,
        description='Whether tool results require the `name` field. Default: auto-detected from URL.',
    )
    sendSessionAffinityHeaders: bool | None = Field(
        None,
        description='Whether to send known session-affinity headers (`session_id`, `x-client-request-id`, `x-session-affinity`) from `options.sessionId` when caching is enabled. Default: false.',
    )
    supportsDeveloperRole: bool | None = Field(
        None,
        description='Whether the provider supports the `developer` role (vs `system`). Default: auto-detected from URL.',
    )
    supportsLongCacheRetention: bool | None = Field(
        None,
        description='Whether the provider supports long prompt cache retention (`prompt_cache_retention: "24h"` or Anthropic-style `cache_control.ttl: "1h"`, depending on format). Default: true.',
    )
    supportsReasoningEffort: bool | None = Field(
        None,
        description='Whether the provider supports `reasoning_effort`. Default: auto-detected from URL.',
    )
    supportsStore: bool | None = Field(
        None,
        description='Whether the provider supports the `store` field. Default: auto-detected from URL.',
    )
    supportsStrictMode: bool | None = Field(
        None,
        description='Whether the provider supports the `strict` field in tool definitions. Default: true.',
    )
    supportsUsageInStreaming: bool | None = Field(
        None,
        description='Whether the provider supports `stream_options: { include_usage: true }` for token usage in streaming responses. Default: true.',
    )
    thinkingFormat: ThinkingFormat | None = Field(
        None,
        description='Format for reasoning/thinking parameter. "openai" uses reasoning_effort, "openrouter" uses reasoning: { effort }, "deepseek" uses thinking: { type } plus reasoning_effort when supported, "together" uses reasoning: { enabled } plus reasoning_effort when supported, "zai" uses top-level enable_thinking: boolean, "qwen" uses top-level enable_thinking: boolean, "qwen-chat-template" uses chat_template_kwargs.enable_thinking, "string-thinking" uses top-level thinking: string, and "ant-ling" uses reasoning: { effort } only when the mapped effort is non-null. Default: "openai".',
    )
    vercelGatewayRouting: VercelGatewayRouting | None = Field(
        None,
        description='Vercel AI Gateway routing preferences. Only used when baseUrl points to Vercel AI Gateway.',
    )
    zaiToolStream: bool | None = Field(
        None,
        description='Whether z.ai supports top-level `tool_stream: true` for streaming tool call deltas. Default: false.',
    )


class SetThinkingLevelCommand(BaseModel):
    id: str | None = None
    level: ThinkingLevel
    type: Literal['set_thinking_level']


class RpcCommand(
    RootModel[
        PromptCommand
        | SteerCommand
        | FollowUpCommand
        | AbortCommand
        | NewSessionCommand
        | GetStateCommand
        | SetModelCommand
        | CycleModelCommand
        | GetAvailableModelsCommand
        | SetThinkingLevelCommand
        | CycleThinkingLevelCommand
        | SetSteeringModeCommand
        | SetFollowUpModeCommand
        | CompactCommand
        | SetAutoCompactionCommand
        | SetAutoRetryCommand
        | AbortRetryCommand
        | BashCommand
        | AbortBashCommand
        | GetSessionStatsCommand
        | ExportHtmlCommand
        | SwitchSessionCommand
        | ForkCommand
        | CloneCommand
        | GetForkMessagesCommand
        | GetLastAssistantTextCommand
        | SetSessionNameCommand
        | GetMessagesCommand
        | GetCommandsCommand
    ]
):
    root: (
        PromptCommand
        | SteerCommand
        | FollowUpCommand
        | AbortCommand
        | NewSessionCommand
        | GetStateCommand
        | SetModelCommand
        | CycleModelCommand
        | GetAvailableModelsCommand
        | SetThinkingLevelCommand
        | CycleThinkingLevelCommand
        | SetSteeringModeCommand
        | SetFollowUpModeCommand
        | CompactCommand
        | SetAutoCompactionCommand
        | SetAutoRetryCommand
        | AbortRetryCommand
        | BashCommand
        | AbortBashCommand
        | GetSessionStatsCommand
        | ExportHtmlCommand
        | SwitchSessionCommand
        | ForkCommand
        | CloneCommand
        | GetForkMessagesCommand
        | GetLastAssistantTextCommand
        | SetSessionNameCommand
        | GetMessagesCommand
        | GetCommandsCommand
    )


class ThinkingLevelResult(BaseModel):
    level: ThinkingLevel


class CycleThinkingLevelResponse(BaseModel):
    command: Literal['cycle_thinking_level']
    data: ThinkingLevelResult | None
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class GetSessionStatsResponse(BaseModel):
    command: Literal['get_session_stats']
    data: SessionStats
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class SourceInfo(BaseModel):
    baseDir: str | None = None
    origin: SourceOrigin
    path: str
    scope: SourceScope
    source: str


class Model(BaseModel):
    api: Any
    baseUrl: str
    compat: OpenAICompletionsCompat | None = Field(
        None,
        description='Compatibility overrides for OpenAI-compatible APIs. If not set, auto-detected from baseUrl.',
    )
    contextWindow: float
    cost: Cost1
    headers: dict[str, str] | None = None
    id: str
    input: list[InputEnum]
    maxTokens: float
    name: str
    provider: KnownProvider | str
    reasoning: bool
    thinkingLevelMap: ThinkingLevelMap | None = Field(
        None,
        description='Maps pi thinking levels to provider/model-specific values. Missing keys use provider defaults. null marks a level as unsupported.',
    )


class AssistantMessage(BaseModel):
    api: KnownApi | str
    content: list[TextContent | ThinkingContent | ToolCall]
    diagnostics: list[AssistantMessageDiagnostic] | None = None
    errorMessage: str | None = None
    model: str
    provider: KnownProvider | str
    responseId: str | None = None
    responseModel: str | None = None
    role: Literal['assistant']
    stopReason: StopReason
    timestamp: float
    usage: Usage


class AssistantMessageStart(BaseModel):
    partial: AssistantMessage
    type: Literal['start']


class AssistantMessageTextStart(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    type: Literal['text_start']


class AssistantMessageTextDelta(BaseModel):
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['text_delta']


class AssistantMessageTextEnd(BaseModel):
    content: str
    contentIndex: float
    partial: AssistantMessage
    type: Literal['text_end']


class AssistantMessageThinkingStart(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    type: Literal['thinking_start']


class AssistantMessageThinkingDelta(BaseModel):
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['thinking_delta']


class AssistantMessageThinkingEnd(BaseModel):
    content: str
    contentIndex: float
    partial: AssistantMessage
    type: Literal['thinking_end']


class AssistantMessageToolcallStart(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    type: Literal['toolcall_start']


class AssistantMessageToolcallDelta(BaseModel):
    contentIndex: float
    delta: str
    partial: AssistantMessage
    type: Literal['toolcall_delta']


class AssistantMessageToolcallEnd(BaseModel):
    contentIndex: float
    partial: AssistantMessage
    toolCall: ToolCall
    type: Literal['toolcall_end']


class AssistantMessageDone(BaseModel):
    message: AssistantMessage
    reason: AssistantFinishReason = Field(..., title='AssistantFinishReason')
    type: Literal['done']


class AssistantMessageError(BaseModel):
    error: AssistantMessage
    reason: AssistantErrorReason = Field(..., title='AssistantErrorReason')
    type: Literal['error']


class SetModelResponse(BaseModel):
    command: Literal['set_model']
    data: Model
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class CycleModelResult(BaseModel):
    isScoped: bool
    model: Model
    thinkingLevel: ThinkingLevel


class CycleModelResponse(BaseModel):
    command: Literal['cycle_model']
    data: CycleModelResult | None
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class AvailableModelsResult(BaseModel):
    models: list[Model]


class GetAvailableModelsResponse(BaseModel):
    command: Literal['get_available_models']
    data: AvailableModelsResult = Field(..., title='AvailableModelsResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class RpcSessionState(BaseModel):
    autoCompactionEnabled: bool
    followUpMode: FollowUpMode
    isCompacting: bool
    isStreaming: bool
    messageCount: float
    model: Model | None = None
    pendingMessageCount: float
    sessionFile: str | None = None
    sessionId: str
    sessionName: str | None = None
    steeringMode: SteeringMode
    thinkingLevel: ThinkingLevel


class RpcSlashCommand(BaseModel):
    description: str | None = Field(None, description='Human-readable description')
    name: str = Field(..., description='Command name (without leading slash)')
    source: Source = Field(..., description='What kind of command this is')
    sourceInfo: SourceInfo = Field(
        ..., description='Source metadata for the owning resource'
    )


class TurnEndEvent(BaseModel):
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    toolResults: list[ToolResultMessage]
    type: Literal['turn_end']


class MessageStartEvent(BaseModel):
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    type: Literal['message_start']


class MessageUpdateEvent(BaseModel):
    assistantMessageEvent: (
        AssistantMessageStart
        | AssistantMessageTextStart
        | AssistantMessageTextDelta
        | AssistantMessageTextEnd
        | AssistantMessageThinkingStart
        | AssistantMessageThinkingDelta
        | AssistantMessageThinkingEnd
        | AssistantMessageToolcallStart
        | AssistantMessageToolcallDelta
        | AssistantMessageToolcallEnd
        | AssistantMessageDone
        | AssistantMessageError
    ) = Field(
        ...,
        description='Event protocol for AssistantMessageEventStream.\n\nStreams should emit `start` before partial updates, then terminate with either:\n- `done` carrying the final successful AssistantMessage, or\n- `error` carrying the final AssistantMessage with stopReason "error" or "aborted"   and errorMessage.',
    )
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    type: Literal['message_update']


class MessageEndEvent(BaseModel):
    message: UserMessage | AssistantMessage | ToolResultMessage = Field(
        ...,
        description='AgentMessage: Union of LLM messages + custom messages. This abstraction allows apps to add custom message types while maintaining type safety and compatibility with the base LLM messages.',
    )
    type: Literal['message_end']


class AgentEndEvent(BaseModel):
    messages: list[UserMessage | AssistantMessage | ToolResultMessage]
    type: Literal['agent_end']
    willRetry: bool


class AgentSessionEvent(
    RootModel[
        AgentStartEvent
        | TurnStartEvent
        | TurnEndEvent
        | MessageStartEvent
        | MessageUpdateEvent
        | MessageEndEvent
        | ToolExecutionStartEvent
        | ToolExecutionUpdateEvent
        | ToolExecutionEndEvent
        | AgentEndEvent
        | QueueUpdateEvent
        | CompactionStartEvent
        | SessionInfoChangedEvent
        | ThinkingLevelChangedEvent
        | CompactionEndEvent
        | AutoRetryStartEvent
        | AutoRetryEndEvent
    ]
):
    root: (
        AgentStartEvent
        | TurnStartEvent
        | TurnEndEvent
        | MessageStartEvent
        | MessageUpdateEvent
        | MessageEndEvent
        | ToolExecutionStartEvent
        | ToolExecutionUpdateEvent
        | ToolExecutionEndEvent
        | AgentEndEvent
        | QueueUpdateEvent
        | CompactionStartEvent
        | SessionInfoChangedEvent
        | ThinkingLevelChangedEvent
        | CompactionEndEvent
        | AutoRetryStartEvent
        | AutoRetryEndEvent
    ) = Field(
        ..., description='Session-specific events that extend the core AgentEvent'
    )


class GetStateResponse(BaseModel):
    command: Literal['get_state']
    data: RpcSessionState
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class MessagesResult(BaseModel):
    messages: list[UserMessage | AssistantMessage | ToolResultMessage]


class GetMessagesResponse(BaseModel):
    command: Literal['get_messages']
    data: MessagesResult = Field(..., title='MessagesResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class CommandsResult(BaseModel):
    commands: list[RpcSlashCommand]


class GetCommandsResponse(BaseModel):
    command: Literal['get_commands']
    data: CommandsResult = Field(..., title='CommandsResult')
    id: str | None = None
    success: Literal[True]
    type: Literal['response']


class RpcResponse(
    RootModel[
        PromptResponse
        | SteerResponse
        | FollowUpResponse
        | AbortResponse
        | NewSessionResponse
        | GetStateResponse
        | SetModelResponse
        | CycleModelResponse
        | GetAvailableModelsResponse
        | SetThinkingLevelResponse
        | CycleThinkingLevelResponse
        | SetSteeringModeResponse
        | SetFollowUpModeResponse
        | CompactResponse
        | SetAutoCompactionResponse
        | SetAutoRetryResponse
        | AbortRetryResponse
        | BashResponse
        | AbortBashResponse
        | GetSessionStatsResponse
        | ExportHtmlResponse
        | SwitchSessionResponse
        | ForkResponse
        | CloneResponse
        | GetForkMessagesResponse
        | GetLastAssistantTextResponse
        | SetSessionNameResponse
        | GetMessagesResponse
        | GetCommandsResponse
        | RpcErrorResponse
    ]
):
    root: (
        PromptResponse
        | SteerResponse
        | FollowUpResponse
        | AbortResponse
        | NewSessionResponse
        | GetStateResponse
        | SetModelResponse
        | CycleModelResponse
        | GetAvailableModelsResponse
        | SetThinkingLevelResponse
        | CycleThinkingLevelResponse
        | SetSteeringModeResponse
        | SetFollowUpModeResponse
        | CompactResponse
        | SetAutoCompactionResponse
        | SetAutoRetryResponse
        | AbortRetryResponse
        | BashResponse
        | AbortBashResponse
        | GetSessionStatsResponse
        | ExportHtmlResponse
        | SwitchSessionResponse
        | ForkResponse
        | CloneResponse
        | GetForkMessagesResponse
        | GetLastAssistantTextResponse
        | SetSessionNameResponse
        | GetMessagesResponse
        | GetCommandsResponse
        | RpcErrorResponse
    )
